version: '3.8'

services:
  #database service
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  #phpmyadmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - '8080:80'

  #redis service
  redis:
    container_name: redis
    image: redis:5
    networks:
      - api-network

  #api service
  api:
    container_name: ms-api
    build:
      context: .
      target: development
    networks:
      - api-network
    ports:
      - 3001:3001
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mysqldb
      - redis
    volumes:
      - .:/app

networks:
  api-network:

volumes:
  mysql:
