version: '3.8'

services:
  #database service
  mysql_db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    # volumes:
    #   - mysql:/var/lib/mysql
    restart: unless-stopped

  #phpmyadmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql_db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - '8080:80'

  #redis service
  redis:
    container_name: redis
    image: redis:5

  #api service
  api:
    container_name: donnet-api
    build:
      context: .
      target: development
    ports:
      - 3001:5000
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mysql_db
      - redis
    volumes:
      - .:/app
      - '/app/node_modules'

volumes:
  mysql:
